[package]
name = "mandelbrot_video"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0"
image = "0.25.8"
metal = "0.32.0"
objc = "0.2"
serde = { version = "1.0", features = ["derive"] }
toml = "0.9"
indicatif = "0.18"
rayon = "1.11.0"  # 新增：进度条库