[rendering]
width = 3840
height = 2160
fps = 60
total_frames = 300

[mandelbrot]
center_x = -0.74364388703
center_y = 0.13182590421
initial_radius = 2.0
zoom_factor = 1.04
initial_iterations = 2000
max_iterations = 100000
iteration_growth_factor = 1.01